# Generated by Django 4.2.9 on 2024-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='out_file',
            field=models.FileField(blank=True, null=True, upload_to='files/results/'),
        ),
    ]
